### ISSUE TITLE
effect_update_depth_exceeded - Maximum update depth exceeded

### ISSUE THREAD

**Issue by timoanttila** [iconify/iconify#386]
Thank you very much for this great module. I have used it in many projects so far.

We found a bug. When there is a lot of data using icons, I get a `$effect` error from the `Icon` loop - the same error that occurs when I let the `$effect` content run indefinitely.

effect_update_depth_exceeded

```JSON
  "devDependencies": {
    "@iconify/svelte": "^5.0.0",
    "@sveltejs/vite-plugin-svelte": "^5.1.0",
    "@tailwindcss/vite": "^4.1.11",
    "@tuspe/components": "^1.9.5",
    "@types/eslint": "^9.6.1",
    "@types/js-cookie": "^3.0.6",
    "eslint": "^9.30.1",
    "eslint-config-prettier": "^10.1.5",
    "eslint-plugin-svelte": "^3.10.1",
    "globals": "^16.3.0",
    "prettier": "^3.6.2",
    "prettier-plugin-svelte": "^3.4.0",
    "svelte-check": "^4.2.2",
    "svelte-preprocess": "^6.0.3",
    "tailwindcss": "^4.1.11",
    "typescript": "^5.8.3",
    "typescript-eslint": "^8.35.1"
  },
  "dependencies": {
    "@sveltejs/adapter-cloudflare": "latest",
    "@sveltejs/kit": "^2.21.3",
    "@tinymce/tinymce-svelte": "^3.1.0",
    "@zerodevx/svelte-toast": "^0.9.6",
    "dayjs": "^1.11.13",
    "js-cookie": "^3.0.5",
    "svelte": "^5.33.18",
    "vite": "^6.3.5"
  }
```

## My Icon.svelte

I have used this with and without `onMount`.

```TypeScript
<script lang="ts">
  import {onMount} from 'svelte'
  import Icon from '@iconify/svelte'

  interface Props {
    icon: string
    isActive?: boolean
    label?: string | undefined
    size?: number
    small?: boolean
  }
  let {icon, isActive, label, size, small = false}: Props = $props(),
    classes = $state(`${icon} self-center`),
    height = $state(28),
    width = $state(28)

  onMount(() => {
    if (label) {
      height = 20
      width = 20
    } else if (small) {
      height = 18
      width = 18
    } else if (size) {
      height = size
      width = size
    }
  })
</script>

{#if !label}
  <Icon class={classes} {icon} {height} {width} />
{:else}
  <div class="flex items-center space-x-2">
    <Icon class={classes} {icon} {height} {width} />
    <span class:front-bold={isActive}>
      {label}
    </span>
  </div>
{/if}
```

**Comment by timoanttila** [comment]
Our development environment works fine with no issues, but some of our biggest clients had problems because they apparently have too many items using this module. I don't know the easiest way to reproduce this, since the app requires a lot of data that uses icons. Even though the icons are downloaded from an external server, one would think they are only fetched once per icon. We only use a few per item, and the same icons are used for all items.

**Comment by timoanttila** [comment]
> Are you displaying thousands of icons at the same time?

I think it's more like hundreds of items, each with one or more icons. We used to have manual components with embedded SVG code. Since we have many icons, I thought it would be better to use an icon library. I had no issues displaying all the items or using manual SVG code for them.

If all the items are fetched once and then cached, the number of items shouldn't be an issue, since they use the same icons and the frontend loads them only once, no matter how many times they're used in the same view.

**Comment by cyberalien** [comment]
Closing this issue because it cannot be reproduced

**Comment by marianboda** [comment]
I got this error too when too many icons (few thousand) were displayed. The problem happens for me when those icons are displayed inside paneforge pane.

**Comment by cyberalien** [comment]
I did more testing, managed to recreate issue once, but it was only once and cannot recreate it again. Though it means there is an issue, so I've researched what can trigger this issue and changed code a bit.

Will do more testing, if I can't trigger this issue again with new code, I'll publish an update. However it does not guarantee that issue is fixed because it cannot be reliably recreated.

Changes:
- Switched from `$effect` to `$derived.by` to update icon data
- Triggering `onload` callback on next tick instead of instant

**Comment by cyberalien** [comment]
Published `5.0.1` with changes. I hope this is enough to fix error. If you'll see error again, please post it here, but I'm not sure what else can be done without being able to reliably trigger error.

**Comment by marianboda** [comment]
Thanks for a quick response. As far as I can tell, this update didn't fix the issue. I can try to create a minimal reproduction repo, but earliest on Monday.

**Comment by cyberalien** [comment]
Thanks.

No rush. I'll be away for few days without computer anyway.
